#pragma config(Sensor, dgtl1,  led1,           sensorDigitalOut)
#pragma config(Sensor, dgtl2,  led2,           sensorDigitalOut)
#pragma config(Sensor, dgtl3,  led3,           sensorDigitalOut)
#pragma config(Motor,  port5,           backRight,     tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, None, 1000)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           frontRight,    tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, None, 1000)
#pragma config(Motor,  port8,           frontLeft,     tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void pre_auton()
{

}

void tankDrive(int left, int right) {
  motor[backLeft] = motor[frontLeft] = left;
  motor[backRight] = motor[frontRight] = right;
}

void arcadeDrive(int forward, int turn) {
  motor[backLeft] = motor[frontLeft] = forward + turn;
  motor[backRight] = motor[frontRight] = forward - turn;
}

task autonomous()
{

}

task usercontrol()
{
	while (true)
	{
	  arcadeDrive(VexRT[Ch3], VexRT[Ch4]);
	}
}
